typo fix in getting_started.html
scala-network/scala-pool pull request #5
Opened 2021-03-24 18:05 UTC by halftime

2021-03-26 09:24 UTC, krazymaez6 requested changes
i wish i was cool like this n help out somehow i am very uneducated but i want to try to contribute to scala project how ever i can but i might need guildence i couldnt even set up mining on my laptop yet

2021-03-27 02:25 UTC, krazymaez6 commented
Error 504
Ray ID: 6365009e7872ed7b •
2021-03-27 01:56:28 UTC
Gateway time-out at host explorer.salaproject.io

2021-03-28 06:25 UTC, krazymaez6 approved these changes
That is spelled wrong.

2021-03-30 15:32 UTC, ahmyi approved these changes

2021-03-30 15:45 UTC, merged